### ISSUE TITLE
Warning: tag 3C is not supported

### ISSUE THREAD

**Issue by askinucuncu** [Riscure/python-trsfile#7] opened 2021-02-10 13:30 UTC
Hi.
I get the following error. How can I solve it?

NotImplementedError: Warning: tag 3C is not supported by the library, please submit an issue on Github.

**Comment by johan-riscure** [comment] 2021-02-10 13:33
Duplicate of #5

**Closed** 2021-02-10 13:33 UTC

**Comment by askinucuncu** [comment] 2021-02-10 13:55
The answer here didn't help. File utf-8, in xml format

**Comment by johan-riscure** [comment] 2021-02-10 13:59
You're trying to open a different file format, this is not a library for xml files

**Comment by askinucuncu** [comment] 2021-02-10 14:14
Screen

<img width="922" alt="Ekran Resmi 2021-02-10 17 12 51" src="https://user-images.githubusercontent.com/39953930/107521193-50017680-6bc3-11eb-9ec7-62d6b2690c0c.png">
<img width="922" alt="Ekran Resmi 2021-02-10 17 13 26" src="https://user-images.githubusercontent.com/39953930/107521199-5132a380-6bc3-11eb-8766-2a54d0d65643.png">

**Comment by johan-riscure** [comment] 2021-02-10 14:49
Again, this is **not** a library for the file format you're using. Looks like it is some annotation for an audio file, perhaps from rosetta stone? This library has nothing to do with that, so you're in the wrong place.
